export const receiptModel = {
  success: true,
  data: {
    issuer_nif: "514781513",
    buyer_nif: "513466010",
    issuer_country: "PT",
    document_type: "FR",
    vat_regime: "N",
    document_date: "20250601",
    document_id: "FR 003/20322",
    hash_code: "JF6PSHBV-20322",
    buyer_country: "PT",
    normal_taxable_base: 60.09,
    normal_vat_value: 7.81,
    total_vat: 7.81,
    total_amount: 67.9,
    software_certificate: "fsSP",
    exemption_reason_code: "71",
    document_date_formatted: "01/06/2025",
    document_type_description: "Fatura",
    vat_regime_description: "Regime Normal",
    issuer_vat_validation: {
      name: "INDEXBRIGADE - LDA",
      address: "RUA DAS OLIVEIRAS 131 TORRE\nCASCAIS\n2750-752 CASCAIS",
      validation_performed: true,
      country_supported: true,
    },
    buyer_vat_validation: {
      name: "DIOGO SERRANO - PRESTAÇÃO DE SERVIÇOS, LDA",
      address: "PRACETA CAI AGUA N 46 1 ESQ\nESTORIL\n2765-555 ESTORIL",
      validation_performed: true,
      country_supported: true,
    },
  },
};
